name: flutter_map_animations
description: Animation utilities for markers and controls of the flutter_map package.
version: 0.3.0
homepage: https://github.com/xSILENCEx/flutter_map_animations
repository: https://github.com/xSILENCEx/flutter_map_animations
issue_tracker: https://github.com/xSILENCEx/flutter_map_animations/issues
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map:                         #地图
    git:
      url: https://github.com/xSILENCEx/flutter_map
      ref: master
  latlong2: ^0.8.1

dev_dependencies:
  fd_lints: ^1.0.2
  flutter_test:
    sdk: flutter
