name: flutter_map_animations
description: Animation utilities for markers and controls of the flutter_map package.
version: 0.3.0
homepage: https://github.com/TesteurManiak/flutter_map_animations
repository: https://github.com/TesteurManiak/flutter_map_animations
issue_tracker: https://github.com/TesteurManiak/flutter_map_animations/issues

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^4.0.0
  latlong2: ^0.8.1

dev_dependencies:
  fd_lints: ^1.0.2
  flutter_test:
    sdk: flutter
